### ISSUE TITLE
Bankroll Invest/Divest Bug

### ISSUE THREAD

**Issue by thegrouchbab** [bustabit/bustabit-client#51] opened 2017-03-01 04:58 UTC
After investing and divesting a few times in a row it appears to not reset the amount I invested and continues to build the site bankroll total.

For example. I invested and divested ~90btc multiple times. It said I had around 450btc invested and when I divest all I actually get back ~90btc (the correct amount), but the site bankroll continues to register it as invested even after divestment.

I will continue to do it and see how far I can walk it up.

bab username:
thegrouch

**Comment by RHavar** [comment] 2017-03-01 05:42
I think the issue was caused by when you divest X it actually increased the bankroll by X (instead of decreasing it). However this only affected the in-memory version, and the database itself should be fine (So a restart of the server should put everything back to normal).

I'm marking this as closed (just pushed a fix),  but if you can reproduce it please open

**Closed by RHavar** 2017-03-01 05:42 UTC
